### PR TITLE
Updated To 3.20.0 (Protocol 440)

### PR DESCRIPTION
**Pull request by JoshuaPHYT**
Updated to Minecraft 1.17.0 (NEW UPDATE)

### CODE REVIEW

**Comment by HimbeersaftLP** [comment]
Thanks

**Comment by HimbeersaftLP** [comment]
no wait

**Comment by HimbeersaftLP** [comment]
You updated the API instead of the version bruh

**Comment by JoshuaPHYT** [comment]
what? omg sorry. let me change ut

**Comment by HimbeersaftLP** [comment]
no, I did already

**Comment by JoshuaPHYT** [comment]
I make it API 3.0.0 so it's compatible on all version on my latest pr

**Pull request merged**
